@url = http://localhost:3000/api/tag
@http_proto = HTTP/1.1

### create tag

POST  {{url}} {{http_proto}}
Content-Type: application/json

{
  "tag_name": "Node.js"
}

### get all tags
GET {{url}} {{http_proto}} 

### get tag by name
GET {{url}}/name/测试 HTTP/1.1



### get tag info by tid

GET {{url}}/5a6847112f354009b5de39a2101ed3e0 HTTP/1.1