@url = http://localhost:3000/api/user
@http_proto = HTTP/1.1

### create user
POST {{url}}/create/admin {{http_proto}}
Content-Type: application/json

{
  "username": "Lionel",
  "password": "yzsYZS",
  "email": "y_lionel@163.com"
}

### get user list
POST  {{url}}/test {{http_proto}}
Content-Type: application/json

{
  "username": "Lionel",
  "email": "y_lionel@163.com"
}


### 
POST http://localhost:3000/auth/admin/login {{http_proto}}
Content-Type: application/json

{
  "username": "Lionel",
  "password": "yzsYZS"
}