@url = http://localhost:3000/api/user
@http_proto = HTTP/1.1

### create user
POST {{url}} {{http_proto}}
Content-Type: application/json

{
  "username": "user3",
  "password": "123",
  "tel": "123",
  "mail": "123"
}

### get user list
GET {{url}} {{http_proto}}